### ISSUE TITLE
setMaxListener issue

### ISSUE THREAD

**Issue by mcollina** [nearform/micro-services-tutorial-iot#44]
(node) warning: possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:239:17)
    at WriteStream.Readable.on (_stream_readable.js:673:33)
    at WriteStream.once (events.js:265:8)
    at DestroyableTransform.Readable.pipe (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/fuge-runner/node_modules/split2/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:567:8)
    at Object.streamOutput (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/fuge-runner/lib/util.js:98:22)
    at /Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/fuge-runner/lib/system.js:148:20
    at run (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/fuge-runner/lib/processRunner.js:143:5)
    at Object.start (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/fuge-runner/lib/processRunner.js:165:9)
    at /Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/fuge-runner/lib/system.js:135:25
    at /Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/fuge-runner/node_modules/async/lib/async.js:246:17
running: __proxy
(node) warning: possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:239:17)
    at WriteStream.Readable.on (_stream_readable.js:673:33)
    at MuteStream.Stream.pipe (stream.js:45:8)
    at MuteStream.pipe (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/node_modules/readline2/node_modules/mute-stream/mute.js:89:32)
    at Object.Interface.createInterface (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/node_modules/readline2/index.js:30:6)
    at module.exports (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/lib/ui/baseUI.js:14:30)
    at new module.exports (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/lib/ui/prompt.js:15:8)
    at Object.promptModule [as prompt](/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/lib/inquirer.js:27:14)
    at UI.prompt (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/dist/ui.js:210:27)
    at EventEmitter.vorpal._prompt (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/dist/vorpal.js:611:15)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:239:17)
    at WriteStream.Readable.on (_stream_readable.js:673:33)
    at MuteStream.Stream.pipe (stream.js:79:8)
    at MuteStream.pipe (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/node_modules/readline2/node_modules/mute-stream/mute.js:89:32)
    at Object.Interface.createInterface (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/node_modules/readline2/index.js:30:6)
    at module.exports (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/lib/ui/baseUI.js:14:30)
    at new module.exports (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/lib/ui/prompt.js:15:8)
    at Object.promptModule [as prompt](/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/lib/inquirer.js:27:14)
    at UI.prompt (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/dist/ui.js:210:27)
    at EventEmitter.vorpal._prompt (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/dist/vorpal.js:611:15)
(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:239:17)
    at WriteStream.Readable.on (_stream_readable.js:673:33)
    at MuteStream.Stream.pipe (stream.js:101:8)
    at MuteStream.pipe (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/node_modules/readline2/node_modules/mute-stream/mute.js:89:32)
    at Object.Interface.createInterface (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/node_modules/readline2/index.js:30:6)
    at module.exports (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/lib/ui/baseUI.js:14:30)
    at new module.exports (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/lib/ui/prompt.js:15:8)
    at Object.promptModule [as prompt](/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/node_modules/inquirer/lib/inquirer.js:27:14)
    at UI.prompt (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/dist/ui.js:210:27)
    at EventEmitter.vorpal._prompt (/Users/matteo/.nvm/versions/node/v4.4.5/lib/node_modules/fuge/node_modules/vorpal/dist/vorpal.js:611:15)

**Comment by mcdonnelldean** [comment]
This is a general Seneca bug. Not specific to this workshop
